### ISSUE TITLE
Training fails specifying a list of Hugging Face datasets

### ISSUE THREAD

**Issue by ivanfioravanti** [ml-explore/mlx-lm#59]
When a list of datasets is specified in config like

```
hf_dataset:
  - path: "Open-Orca/OpenOrca"
    train_split: "train[:90%]"
    valid_split: "train[-10%:]"
    prompt_feature: "question"
    completion_feature: "response"
  - path: "trl-lib/ultrafeedback_binarized"
    train_split: "train[:90%]"
    valid_split: "train[-10%:]"
    chat_feature: "chosen"
```
Following error occurs: AttributeError: 'ConcatenatedDataset' object has no attribute 'process'.

I'm investigating.
